# Generated by Django 3.2.4 on 2021-06-17 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('place', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('volume', models.FloatField(choices=[(0.2, 'small'), (0.3, 'medium'), (0.5, 'large')], default=0.2)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='box.coffeetype')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='box.coffeepoint')),
            ],
            options={
                'ordering': ('done', '-created'),
            },
        ),
        migrations.AddField(
            model_name='coffeepoint',
            name='coffee',
            field=models.ManyToManyField(related_name='points', to='box.CoffeeType'),
        ),
    ]
