# Generated by Django 3.2.4 on 2021-06-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxes',
            new_name='Box',
        ),
    ]
