# Generated by Django 3.2.4 on 2021-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_coffeepoint_coffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=64),
        ),
    ]
