# Generated by Django 3.2.4 on 2021-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_auto_20210617_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.FloatField(choices=[(0.2, 'small'), (0.3, 'medium'), (0.5, 'large')], default=0.2),
        ),
    ]
