# Generated by Django 3.2.4 on 2021-06-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('done', '-created')},
        ),
    ]
