# Generated by Django 3.2.4 on 2021-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeepoint',
            name='coffee',
            field=models.ManyToManyField(related_name='points', to='box.CoffeeType'),
        ),
    ]
